/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cpp_linux_CONSTANTS_H
#define cpp_linux_CONSTANTS_H

#include "cpp_linux_types.h"

namespace azure { namespace storage { namespace cpp_linux {

class cpp_linuxConstants {
 public:
  cpp_linuxConstants();

};

extern const cpp_linuxConstants g_cpp_linux_constants;

}}} // namespace

#endif
