/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cpp_linux_constants.h"

namespace azure { namespace storage { namespace cpp_linux {

const cpp_linuxConstants g_cpp_linux_constants;

cpp_linuxConstants::cpp_linuxConstants() {
}

}}} // namespace

